connect e3/e3;

DROP TABLE OCULTA;
DROP TABLE JUICIO;
DROP TABLE VISITAR;
DROP TABLE ATIENDE;
DROP TABLE MERCANTIL;
DROP TABLE CIVIL;
DROP TABLE PENAL;
DROP TABLE ESTUDIANTES;
DROP TABLE ABOGADOS;
DROP TABLE TRAPOS_SUCIOS;
DROP TABLE JUEZ;
DROP TABLE DEMANDANTE;
DROP TABLE EXPEDIENTE;
DROP TABLE CLIENTE;
DROP TABLE TRABAJADORES;

DROP FUNCTION TOTAL_ESTUDIANTES;
DROP FUNCTION TOTAL_CASOS;
DROP PROCEDURE TOTAL_EXPEDIENTES_ABOGADO;
DROP PROCEDURE LISTADO_VISITAS;
DROP TRIGGER INSER_ESTUDIANTE;
DROP TRIGGER INSER_ABOGADO;
DROP TRIGGER INSER_JUICIO;
DROP PROCEDURE LISTADO_CLIEN;
DROP FUNCTION NUM_TRA;
DROP PROCEDURE LISTADO_JUECES;
DROP FUNCTION EDAD_REAL;
DROP TRIGGER COMPROBAR_FECHA;
DROP PROCEDURE NOVATO;

DROP VIEW EXPO_GRAV;
DROP VIEW LIST_CLIEN;
DROP VIEW VIEW_TRAPOS;
DROP VIEW TRAB_00;

CONNECT SYSTEM/bdadmin;
DROP USER e3Estudiante cascade;
DROP USER e3Abogados cascade ;
DROP USER e3Jefe cascade;
DROP USER e3 cascade;














