connect system/bdadmin;
create user e3 identified by e3;
GRANT CONNECT, RESOURCE, CREATE VIEW TO e3;
connect e3/e3;

CREATE TABLE TRABAJADORES(
	CODIGO 				 VARCHAR2(10) CONSTRAINT tra_cod_pk PRIMARY KEY,
	NOMBRE 				 VARCHAR2(10), 
	APELLIDOS 			 VARCHAR2(30),
	FECHA_INI			 DATE CONSTRAINT tra_fec_nn NOT NULL,
	FECHA_NACIMIENTO 	 DATE
);

CREATE TABLE CLIENTE(
	DNI 		 VARCHAR2(9) CONSTRAINT cli_dni_pk PRIMARY KEY,
	NOMBRE 		 VARCHAR2(10),
	APELLIDOS 	 VARCHAR2(30),
	CORREO_ELEC	 VARCHAR2(30),
	DIRECCION 	 VARCHAR2(50)
);

CREATE TABLE DEMANDANTE(
	DNI_DEMANDANTE 		VARCHAR2(9) CONSTRAINT dem_dni_pk PRIMARY KEY,
	NOMBRE_DEMANDANTE 	VARCHAR2(10)
);

CREATE TABLE JUEZ(
	DNI_JUEZ 	 VARCHAR2(9) CONSTRAINT jue_dni_pk PRIMARY KEY,
	NOMBRE 		 VARCHAR2(10),
	APELLIDOS 	 VARCHAR2(30),
	FAMILIARES	 VARCHAR2(50),
	CODIGO 		 VARCHAR2(10) CONSTRAINT jue_cod_nn NOT NULL 
							 CONSTRAINT jue_cod_uq UNIQUE
);

CREATE TABLE TRAPOS_SUCIOS(
	CODIGO_TRAPO 	VARCHAR2(10) CONSTRAINT trap_cod_pk PRIMARY KEY,
	DESCRIPCION 	VARCHAR2(50)
);

CREATE TABLE ABOGADOS(
	trab_codigo 	 VARCHAR2(10) CONSTRAINT abo_tra_pk PRIMARY KEY,
	horario			 VARCHAR2(10),
	colegio_codigo 	 VARCHAR2(10) CONSTRAINT abo_col_nn NOT NULL 
								 CONSTRAINT abo_col_uq UNIQUE,
	CONSTRAINT abo_tra_fk FOREIGN KEY (trab_codigo) REFERENCES TRABAJADORES
);

CREATE TABLE ESTUDIANTES(
	TRAB_CODIGO 		VARCHAR2(10),
	ABO_TRAB_CODIGO 	VARCHAR2(10) CONSTRAINT est_abot_nn NOT NULL,
	CONSTRAINT est_tra_abot_pk PRIMARY KEY (TRAB_CODIGO,ABO_TRAB_CODIGO),
	CONSTRAINT est_abo_fk FOREIGN KEY (ABO_TRAB_CODIGO) REFERENCES ABOGADOS,
	CONSTRAINT est_tra_fk FOREIGN KEY (TRAB_CODIGO) REFERENCES TRABAJADORES
);

CREATE TABLE PENAL(
	COMISIONES 		NUMBER(6,2),
	AB_CODIGO  		VARCHAR2(10),
	CONSTRAINT pen_abc_col_pk PRIMARY KEY (AB_CODIGO),
	CONSTRAINT pen_abo_fk FOREIGN KEY (AB_CODIGO) REFERENCES ABOGADOS
);

CREATE TABLE CIVIL(
	AB_CODIGO  		VARCHAR2(10),
	CONSTRAINT civ_abc_col_pk PRIMARY KEY (AB_CODIGO),
	CONSTRAINT civ_abo_fk FOREIGN KEY (AB_CODIGO) REFERENCES ABOGADOS
);

CREATE TABLE MERCANTIL(
	PUNTOS 			NUMBER(6),
	AB_CODIGO  		VARCHAR2(10),
	CONSTRAINT mer_abc_col_pk PRIMARY KEY (AB_CODIGO),
	CONSTRAINT mer_abo_fk FOREIGN KEY (AB_CODIGO) REFERENCES ABOGADOS
);

CREATE TABLE EXPEDIENTE(
	TIPO_DE_FALTA 		VARCHAR2(10),
	CODIGO_EXPEDIENTE 	VARCHAR2(10),
	CLIEN_DNI 			VARCHAR2(10),
	CONSTRAINT exp_cod_cli_pk PRIMARY KEY (CODIGO_EXPEDIENTE,CLIEN_DNI),
	CONSTRAINT exp_cli_fk FOREIGN KEY (CLIEN_DNI) REFERENCES CLIENTE
);

CREATE TABLE ATIENDE(
	ABO_TRAB_CODIGO 	 VARCHAR2(10),
	CLIEN_DNI			 VARCHAR2(9),
	COD_EXPEDIENTE		 VARCHAR2(10),
	CONSTRAINT ati_abo_cli_cod_pk PRIMARY KEY (ABO_TRAB_CODIGO,CLIEN_DNI,COD_EXPEDIENTE),
	CONSTRAINT ati_abo_fk FOREIGN KEY (ABO_TRAB_CODIGO) REFERENCES ABOGADOS,
	CONSTRAINT ati_exp_fk FOREIGN KEY (COD_EXPEDIENTE,CLIEN_DNI) REFERENCES EXPEDIENTE
);


CREATE TABLE VISITAR (
	DNI_DEMANDANTE 		 VARCHAR2(10),
	ABO_TRAB_CODIGO		 VARCHAR2(10),
	CLIEN_DNI			 VARCHAR2(10),
	COD_EXPEDIENTE		 VARCHAR2(10),
	FECHA_VISITA		 DATE,
	CONSTRAINT vis_dni_abo_cli_cod_pk PRIMARY KEY (DNI_DEMANDANTE,ABO_TRAB_CODIGO,CLIEN_DNI,COD_EXPEDIENTE,FECHA_VISITA),
	CONSTRAINT vis_ati_fk FOREIGN KEY (ABO_TRAB_CODIGO,CLIEN_DNI,COD_EXPEDIENTE) REFERENCES ATIENDE,
	CONSTRAINT vis_dem_fk FOREIGN KEY (DNI_DEMANDANTE) REFERENCES DEMANDANTE
);

CREATE TABLE JUICIO (
	JUEZ_DNI			 VARCHAR2(10) CONSTRAINT jui_jue_nn NOT NULL,
	DNI_DEMANDANTE 		 VARCHAR2(10),
	ABO_TRAB_CODIGO		 VARCHAR2(10),
	CLIEN_DNI			 VARCHAR2(10),
	COD_EXPEDIENTE		 VARCHAR2(10),
	CONSTRAINT jui_juezd_dnid_abo_cli_cod_pk PRIMARY KEY (JUEZ_DNI,DNI_DEMANDANTE,ABO_TRAB_CODIGO,CLIEN_DNI,COD_EXPEDIENTE),
	CONSTRAINT jui_dem_fk FOREIGN KEY (DNI_DEMANDANTE) REFERENCES DEMANDANTE,
	CONSTRAINT jui_jue_fk FOREIGN KEY (JUEZ_DNI) REFERENCES JUEZ
);

CREATE TABLE OCULTA(
	CODIGO_TRAPO VARCHAR2(10),
	JUEZ_DNI 	 VARCHAR2(9),
	CONSTRAINT ocu_cod_jue_pk PRIMARY KEY (CODIGO_TRAPO,JUEZ_DNI),
	CONSTRAINT ocu_jue_fk FOREIGN KEY (JUEZ_DNI) REFERENCES JUEZ,
	CONSTRAINT ocu_trap_fk FOREIGN KEY (CODIGO_TRAPO) REFERENCES TRAPOS_SUCIOS
);